<?php

return [
    'GH' => [
        'alpha3' => 'GHA',
        'numeric' => 288,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Ghana',
        'korean' => '가나',
    ],
    'GA' => [
        'alpha3' => 'GAB',
        'numeric' => 266,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Gabon',
        'korean' => '가봉',
    ],
    'GY' => [
        'alpha3' => 'GUY',
        'numeric' => 328,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Guyana',
        'korean' => '가이아나',
    ],
    'GM' => [
        'alpha3' => 'GMB',
        'numeric' => 270,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Gambia',
        'korean' => '감비아',
    ],
    'GT' => [
        'alpha3' => 'GTM',
        'numeric' => 320,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Guatemala',
        'korean' => '과테말라',
    ],
    'GD' => [
        'alpha3' => 'GRD',
        'numeric' => 308,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Grenada',
        'korean' => '그레나다',
    ],
    'GR' => [
        'alpha3' => 'GRC',
        'numeric' => 300,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Greece',
        'korean' => '그리스',
    ],
    'GN' => [
        'alpha3' => 'GIN',
        'numeric' => 324,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Guinea',
        'korean' => '기니',
    ],
    'GW' => [
        'alpha3' => 'GNB',
        'numeric' => 624,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Guinea-Bissau',
        'korean' => '기니비사우',
    ],
    'NR' => [
        'alpha3' => 'NRU',
        'numeric' => 520,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Nauru',
        'korean' => '나우루',
    ],
    'NG' => [
        'alpha3' => 'NGA',
        'numeric' => 566,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Nigeria',
        'korean' => '나이지리아',
    ],
    'SS' => [
        'alpha3' => 'SSD',
        'numeric' => 728,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'South Sudan',
        'korean' => '남수단',
    ],
    'ZA' => [
        'alpha3' => 'ZAF',
        'numeric' => 710,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'South Africa',
        'korean' => '남아프리카공화국',
    ],
    'NL' => [
        'alpha3' => 'NLD',
        'numeric' => 528,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Netherlands',
        'korean' => '네덜란드',
    ],
    'NP' => [
        'alpha3' => 'NPL',
        'numeric' => 524,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Nepal',
        'korean' => '네팔',
    ],
    'NO' => [
        'alpha3' => 'NOR',
        'numeric' => 578,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Norway',
        'korean' => '노르웨이',
    ],
    'NZ' => [
        'alpha3' => 'NZL',
        'numeric' => 554,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'New Zealand',
        'korean' => '뉴질랜드',
    ],
    'NU' => [
        'alpha3' => 'NIU',
        'numeric' => 570,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '미주',
        'english' => 'Niue',
        'korean' => '니우에',
    ],
    'NE' => [
        'alpha3' => 'NER',
        'numeric' => 562,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Niger',
        'korean' => '니제르',
    ],
    'NI' => [
        'alpha3' => 'NIC',
        'numeric' => 558,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Nicaragua',
        'korean' => '니카라과',
    ],
    'DK' => [
        'alpha3' => 'DNK',
        'numeric' => 208,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Denmark',
        'korean' => '덴마크',
    ],
    'DO' => [
        'alpha3' => 'DOM',
        'numeric' => 214,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Dominican Republic',
        'korean' => '도미니카공화국',
    ],
    'DM' => [
        'alpha3' => 'DMA',
        'numeric' => 212,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Dominica',
        'korean' => '도미니카연방',
    ],
    'DE' => [
        'alpha3' => 'DEU',
        'numeric' => 276,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Germany',
        'korean' => '독일',
    ],
    'TL' => [
        'alpha3' => 'TLS',
        'numeric' => 626,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Timor-Leste',
        'korean' => '동티모르',
    ],
    'LA' => [
        'alpha3' => 'LAO',
        'numeric' => 418,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Laos',
        'korean' => '라오스',
    ],
    'LR' => [
        'alpha3' => 'LBR',
        'numeric' => 430,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Liberia',
        'korean' => '라이베리아',
    ],
    'LV' => [
        'alpha3' => 'LVA',
        'numeric' => 428,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Latvia',
        'korean' => '라트비아',
    ],
    'RU' => [
        'alpha3' => 'RUS',
        'numeric' => 643,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Russia',
        'korean' => '러시아',
    ],
    'LB' => [
        'alpha3' => 'LBN',
        'numeric' => 422,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Lebanon',
        'korean' => '레바논',
    ],
    'LS' => [
        'alpha3' => 'LSO',
        'numeric' => 426,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Lesotho',
        'korean' => '레소토',
    ],
    'RO' => [
        'alpha3' => 'ROU',
        'numeric' => 642,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Romania',
        'korean' => '루마니아',
    ],
    'LU' => [
        'alpha3' => 'LUX',
        'numeric' => 442,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Luxembourg',
        'korean' => '룩셈부르크',
    ],
    'RW' => [
        'alpha3' => 'RWA',
        'numeric' => 646,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Rwanda',
        'korean' => '르완다',
    ],
    'LY' => [
        'alpha3' => 'LBY',
        'numeric' => 434,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Libya',
        'korean' => '리비아',
    ],
    'LT' => [
        'alpha3' => 'LTU',
        'numeric' => 440,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Lithuania',
        'korean' => '리투아니아',
    ],
    'LI' => [
        'alpha3' => 'LIE',
        'numeric' => 438,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Liechtenstein',
        'korean' => '리히텐슈타인',
    ],
    'MG' => [
        'alpha3' => 'MDG',
        'numeric' => 450,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Madagascar',
        'korean' => '마다가스카르',
    ],
    'MH' => [
        'alpha3' => 'MHL',
        'numeric' => 584,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Marshall Islands',
        'korean' => '마셜제도',
    ],
    'FM' => [
        'alpha3' => 'FSM',
        'numeric' => 583,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Federated States of Micronesia',
        'korean' => '마이크로네시아연방',
    ],
    'MW' => [
        'alpha3' => 'MWI',
        'numeric' => 454,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Malawi',
        'korean' => '말라위',
    ],
    'MY' => [
        'alpha3' => 'MYS',
        'numeric' => 458,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Malaysia',
        'korean' => '말레이시아',
    ],
    'ML' => [
        'alpha3' => 'MLI',
        'numeric' => 466,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Mali',
        'korean' => '말리',
    ],
    'MX' => [
        'alpha3' => 'MEX',
        'numeric' => 484,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Mexico',
        'korean' => '멕시코',
    ],
    'MC' => [
        'alpha3' => 'MCO',
        'numeric' => 492,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Monaco',
        'korean' => '모나코',
    ],
    'MA' => [
        'alpha3' => 'MAR',
        'numeric' => 504,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Morocco',
        'korean' => '모로코',
    ],
    'MU' => [
        'alpha3' => 'MUS',
        'numeric' => 480,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Mauritius',
        'korean' => '모리셔스',
    ],
    'MR' => [
        'alpha3' => 'MRT',
        'numeric' => 478,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Mauritania',
        'korean' => '모리타니아',
    ],
    'MZ' => [
        'alpha3' => 'MOZ',
        'numeric' => 508,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Mazambique',
        'korean' => '모잠비크',
    ],
    'ME' => [
        'alpha3' => 'MNE',
        'numeric' => 499,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Montenegro',
        'korean' => '몬테네그로',
    ],
    'MD' => [
        'alpha3' => 'MDA',
        'numeric' => 498,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Moldova',
        'korean' => '몰도바',
    ],
    'MV' => [
        'alpha3' => 'MDV',
        'numeric' => 462,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Maldives',
        'korean' => '몰디브',
    ],
    'MT' => [
        'alpha3' => 'MLT',
        'numeric' => 470,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Malta',
        'korean' => '몰타',
    ],
    'MN' => [
        'alpha3' => 'MNG',
        'numeric' => 496,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Mongolia',
        'korean' => '몽골',
    ],
    'US' => [
        'alpha3' => 'USA',
        'numeric' => 840,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'United States of America',
        'korean' => '미국',
    ],
    'MM' => [
        'alpha3' => 'MMR',
        'numeric' => 104,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Myanmar',
        'korean' => '미얀마',
    ],
    'VU' => [
        'alpha3' => 'VUT',
        'numeric' => 548,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Vanuatu',
        'korean' => '바누아투',
    ],
    'BH' => [
        'alpha3' => 'BHR',
        'numeric' => 48,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Bahrain',
        'korean' => '바레인',
    ],
    'BB' => [
        'alpha3' => 'BRB',
        'numeric' => 52,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Barbados',
        'korean' => '바베이도스',
    ],
    'VA' => [
        'alpha3' => 'VAT',
        'numeric' => 336,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Vatican',
        'korean' => '교황청',
    ],
    'BS' => [
        'alpha3' => 'BHS',
        'numeric' => 44,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Bahamas',
        'korean' => '바하마',
    ],
    'BD' => [
        'alpha3' => 'BGD',
        'numeric' => 50,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Bangladesh',
        'korean' => '방글라데시',
    ],
    'BJ' => [
        'alpha3' => 'BEN',
        'numeric' => 204,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Benin',
        'korean' => '베냉',
    ],
    'VE' => [
        'alpha3' => 'VEN',
        'numeric' => 862,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Venezuela',
        'korean' => '베네수엘라',
    ],
    'VN' => [
        'alpha3' => 'VNM',
        'numeric' => 704,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Vietnam',
        'korean' => '베트남',
    ],
    'BE' => [
        'alpha3' => 'BEL',
        'numeric' => 56,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Belgium',
        'korean' => '벨기에',
    ],
    'BY' => [
        'alpha3' => 'BLR',
        'numeric' => 112,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Belarus',
        'korean' => '벨라루스',
    ],
    'BZ' => [
        'alpha3' => 'BLZ',
        'numeric' => 84,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Belize',
        'korean' => '벨리즈',
    ],
    'BA' => [
        'alpha3' => 'BIH',
        'numeric' => 70,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Bosnia-Herzegovina',
        'korean' => '보스니아헤르체고비나',
    ],
    'BW' => [
        'alpha3' => 'BWA',
        'numeric' => 72,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Botswana',
        'korean' => '보츠와나',
    ],
    'BO' => [
        'alpha3' => 'BOL',
        'numeric' => 68,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Bolivia',
        'korean' => '볼리비아',
    ],
    'BI' => [
        'alpha3' => 'BDI',
        'numeric' => 108,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Burundi',
        'korean' => '부룬디',
    ],
    'BF' => [
        'alpha3' => 'BFA',
        'numeric' => 854,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Burkina Faso',
        'korean' => '부르키나파소',
    ],
    'BT' => [
        'alpha3' => 'BTN',
        'numeric' => 64,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Bhutan',
        'korean' => '부탄',
    ],
    'MK' => [
        'alpha3' => 'MKD',
        'numeric' => 807,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'North Macedonia',
        'korean' => '북마케도니아',
    ],
    'BG' => [
        'alpha3' => 'BGR',
        'numeric' => 100,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Bulgaria',
        'korean' => '불가리아',
    ],
    'BR' => [
        'alpha3' => 'BRA',
        'numeric' => 76,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Brazil',
        'korean' => '브라질',
    ],
    'BN' => [
        'alpha3' => 'BRN',
        'numeric' => 96,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Brunei',
        'korean' => '브루나이',
    ],
    'WS' => [
        'alpha3' => 'WSM',
        'numeric' => 882,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Samoa',
        'korean' => '사모아',
    ],
    'SA' => [
        'alpha3' => 'SAU',
        'numeric' => 682,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Saudi Arabia',
        'korean' => '사우디아라비아',
    ],
    'CY' => [
        'alpha3' => 'CYP',
        'numeric' => 196,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Cyprus',
        'korean' => '사이프러스',
    ],
    'SM' => [
        'alpha3' => 'SMR',
        'numeric' => 674,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'San Marino',
        'korean' => '산마리노',
    ],
    'ST' => [
        'alpha3' => 'STP',
        'numeric' => 678,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'S?o Tom? & Principe',
        'korean' => '상투메프린시페',
    ],
    'SN' => [
        'alpha3' => 'SEN',
        'numeric' => 686,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Senegal',
        'korean' => '세네갈',
    ],
    'RS' => [
        'alpha3' => 'SRB',
        'numeric' => 688,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Serbia',
        'korean' => '세르비아',
    ],
    'SC' => [
        'alpha3' => 'SYC',
        'numeric' => 690,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Seychelles',
        'korean' => '세이셸',
    ],
    'LC' => [
        'alpha3' => 'LCA',
        'numeric' => 662,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'St. Lucia',
        'korean' => '세인트 루시아',
    ],
    'VC' => [
        'alpha3' => 'VCT',
        'numeric' => 670,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'St. Vincent & the Grenadines',
        'korean' => '세인트 빈센트 그레나딘',
    ],
    'KN' => [
        'alpha3' => 'KNA',
        'numeric' => 659,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'St. Kitts-Nevis',
        'korean' => '세인트 키츠 네비스',
    ],
    'SO' => [
        'alpha3' => 'SOM',
        'numeric' => 706,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Somalia',
        'korean' => '소말리아',
    ],
    'SB' => [
        'alpha3' => 'SLB',
        'numeric' => 90,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Solomon Islands',
        'korean' => '솔로몬제도',
    ],
    'SD' => [
        'alpha3' => 'SDN',
        'numeric' => 736,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Sudan',
        'korean' => '수단',
    ],
    'SR' => [
        'alpha3' => 'SUR',
        'numeric' => 740,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Suriname',
        'korean' => '수리남',
    ],
    'LK' => [
        'alpha3' => 'LKA',
        'numeric' => 144,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Sri Lanka',
        'korean' => '스리랑카',
    ],
    'SE' => [
        'alpha3' => 'SWE',
        'numeric' => 752,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Sweden',
        'korean' => '스웨덴',
    ],
    'CH' => [
        'alpha3' => 'CHE',
        'numeric' => 756,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Swiss',
        'korean' => '스위스',
    ],
    'ES' => [
        'alpha3' => 'ESP',
        'numeric' => 724,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Spain',
        'korean' => '스페인',
    ],
    'SK' => [
        'alpha3' => 'SVK',
        'numeric' => 703,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Slovakia',
        'korean' => '슬로바키아',
    ],
    'SI' => [
        'alpha3' => 'SVN',
        'numeric' => 705,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Slovenia',
        'korean' => '슬로베니아',
    ],
    'SY' => [
        'alpha3' => 'SYR',
        'numeric' => 760,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Syria',
        'korean' => '시리아',
    ],
    'SL' => [
        'alpha3' => 'SLE',
        'numeric' => 694,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Sierra Leone',
        'korean' => '시에라리온',
    ],
    'SG' => [
        'alpha3' => 'SGP',
        'numeric' => 702,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Singapore',
        'korean' => '싱가포르',
    ],
    'AE' => [
        'alpha3' => 'ARE',
        'numeric' => 784,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'United Arab Emirates : UAE',
        'korean' => '아랍에미리트',
    ],
    'AM' => [
        'alpha3' => 'ARM',
        'numeric' => 51,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Armenia',
        'korean' => '아르메니아',
    ],
    'AR' => [
        'alpha3' => 'ARG',
        'numeric' => 32,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Argentina',
        'korean' => '아르헨티나',
    ],
    'IS' => [
        'alpha3' => 'ISL',
        'numeric' => 352,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Iceland',
        'korean' => '아이슬란드',
    ],
    'HT' => [
        'alpha3' => 'HTI',
        'numeric' => 332,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Haiti',
        'korean' => '아이티',
    ],
    'IE' => [
        'alpha3' => 'IRL',
        'numeric' => 372,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Ireland',
        'korean' => '아일랜드',
    ],
    'AZ' => [
        'alpha3' => 'AZE',
        'numeric' => 31,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Azerbaijan',
        'korean' => '아제르바이잔',
    ],
    'AF' => [
        'alpha3' => 'AFG',
        'numeric' => 4,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Afghanistan',
        'korean' => '아프가니스탄',
    ],
    'AD' => [
        'alpha3' => 'AND',
        'numeric' => 20,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Andorra',
        'korean' => '안도라',
    ],
    'AL' => [
        'alpha3' => 'ALB',
        'numeric' => 8,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Albania',
        'korean' => '알바니아',
    ],
    'DZ' => [
        'alpha3' => 'DZA',
        'numeric' => 12,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Algeria',
        'korean' => '알제리',
    ],
    'AO' => [
        'alpha3' => 'AGO',
        'numeric' => 24,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Angola',
        'korean' => '앙골라',
    ],
    'AG' => [
        'alpha3' => 'ATG',
        'numeric' => 28,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Antigua and Barbuda',
        'korean' => '앤티가바부다',
    ],
    'ER' => [
        'alpha3' => 'ERI',
        'numeric' => 232,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Eritrea',
        'korean' => '에리트레아',
    ],
    'SZ' => [
        'alpha3' => 'SWZ',
        'numeric' => 748,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Eswatini',
        'korean' => '에스와티니',
    ],
    'EE' => [
        'alpha3' => 'EST',
        'numeric' => 233,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Estonia',
        'korean' => '에스토니아',
    ],
    'EC' => [
        'alpha3' => 'ECU',
        'numeric' => 218,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Ecuador',
        'korean' => '에콰도르',
    ],
    'ET' => [
        'alpha3' => 'ETH',
        'numeric' => 231,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Ethiopia',
        'korean' => '에티오피아',
    ],
    'SV' => [
        'alpha3' => 'SLV',
        'numeric' => 222,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'El Salvador',
        'korean' => '엘살바도르',
    ],
    'GB' => [
        'alpha3' => 'GBR',
        'numeric' => 826,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'United Kingdom',
        'korean' => '영국',
    ],
    'YE' => [
        'alpha3' => 'YEM',
        'numeric' => 887,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Yemen',
        'korean' => '예멘',
    ],
    'OM' => [
        'alpha3' => 'OMN',
        'numeric' => 512,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Oman',
        'korean' => '오만',
    ],
    'AT' => [
        'alpha3' => 'AUT',
        'numeric' => 40,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Austria',
        'korean' => '오스트리아',
    ],
    'HN' => [
        'alpha3' => 'HND',
        'numeric' => 340,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Honduras',
        'korean' => '온두라스',
    ],
    'JO' => [
        'alpha3' => 'JOR',
        'numeric' => 400,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Jordan',
        'korean' => '요르단',
    ],
    'UG' => [
        'alpha3' => 'UGA',
        'numeric' => 800,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Uganda',
        'korean' => '우간다',
    ],
    'UY' => [
        'alpha3' => 'URY',
        'numeric' => 858,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Uruguay',
        'korean' => '우루과이',
    ],
    'UZ' => [
        'alpha3' => 'UZB',
        'numeric' => 860,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Uzbekistan',
        'korean' => '우즈베키스탄',
    ],
    'UA' => [
        'alpha3' => 'UKR',
        'numeric' => 804,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Ukraine',
        'korean' => '우크라이나',
    ],
    'IQ' => [
        'alpha3' => 'IRQ',
        'numeric' => 368,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Iraq',
        'korean' => '이라크',
    ],
    'IR' => [
        'alpha3' => 'IRN',
        'numeric' => 364,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Iran',
        'korean' => '이란',
    ],
    'IL' => [
        'alpha3' => 'ISR',
        'numeric' => 376,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Israel',
        'korean' => '이스라엘',
    ],
    'EG' => [
        'alpha3' => 'EGY',
        'numeric' => 818,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Egypt',
        'korean' => '이집트',
    ],
    'IT' => [
        'alpha3' => 'ITA',
        'numeric' => 380,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Italia',
        'korean' => '이탈리아',
    ],
    'IN' => [
        'alpha3' => 'IND',
        'numeric' => 356,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'India',
        'korean' => '인도',
    ],
    'ID' => [
        'alpha3' => 'IDN',
        'numeric' => 360,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Indonesia',
        'korean' => '인도네시아',
    ],
    'JP' => [
        'alpha3' => 'JPN',
        'numeric' => 392,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Japan',
        'korean' => '일본',
    ],
    'JM' => [
        'alpha3' => 'JAM',
        'numeric' => 388,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Jamaica',
        'korean' => '자메이카',
    ],
    'ZM' => [
        'alpha3' => 'ZMB',
        'numeric' => 894,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Zambia',
        'korean' => '잠비아',
    ],
    'GQ' => [
        'alpha3' => 'GNQ',
        'numeric' => 226,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Equatorial Guinea',
        'korean' => '적도기니',
    ],
    'GE' => [
        'alpha3' => 'GEO',
        'numeric' => 268,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Georgia',
        'korean' => '조지아',
    ],
    'CN' => [
        'alpha3' => 'CHN',
        'numeric' => 156,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'China',
        'korean' => '중국',
    ],
    'CF' => [
        'alpha3' => 'CAF',
        'numeric' => 140,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Central African Republic',
        'korean' => '중앙아프리카공화국',
    ],
    'DJ' => [
        'alpha3' => 'DJI',
        'numeric' => 262,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Djibouti',
        'korean' => '지부티',
    ],
    'ZW' => [
        'alpha3' => 'ZWE',
        'numeric' => 716,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Zimbabwe',
        'korean' => '짐바브웨',
    ],
    'TD' => [
        'alpha3' => 'TCD',
        'numeric' => 148,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Chad',
        'korean' => '차드',
    ],
    'CZ' => [
        'alpha3' => 'CZE',
        'numeric' => 203,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Czech',
        'korean' => '체코',
    ],
    'CL' => [
        'alpha3' => 'CHL',
        'numeric' => 152,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Chile',
        'korean' => '칠레',
    ],
    'CM' => [
        'alpha3' => 'CMR',
        'numeric' => 120,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Cameroon',
        'korean' => '카메룬',
    ],
    'CV' => [
        'alpha3' => 'CPV',
        'numeric' => 132,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Cape Verde',
        'korean' => '카보베르데',
    ],
    'KZ' => [
        'alpha3' => 'KAZ',
        'numeric' => 398,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Kazakhstan',
        'korean' => '카자흐스탄',
    ],
    'QA' => [
        'alpha3' => 'QAT',
        'numeric' => 634,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Qatar',
        'korean' => '카타르',
    ],
    'KH' => [
        'alpha3' => 'KHM',
        'numeric' => 116,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Cambodia',
        'korean' => '캄보디아',
    ],
    'CA' => [
        'alpha3' => 'CAN',
        'numeric' => 124,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Canada',
        'korean' => '캐나다',
    ],
    'KE' => [
        'alpha3' => 'KEN',
        'numeric' => 404,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Kenya',
        'korean' => '케냐',
    ],
    'KM' => [
        'alpha3' => 'COM',
        'numeric' => 174,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Comoros',
        'korean' => '코모로',
    ],
    'XK' => [
        'alpha3' => 'XKX',
        'numeric' => 383,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Kosovo',
        'korean' => '코소보',
    ],
    'CR' => [
        'alpha3' => 'CRI',
        'numeric' => 188,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Costa Rica',
        'korean' => '코스타리카',
    ],
    'CI' => [
        'alpha3' => 'CIV',
        'numeric' => 384,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => "Cote D'Ivoire",
        'korean' => '코트디부아르',
    ],
    'CO' => [
        'alpha3' => 'COL',
        'numeric' => 170,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Colombia',
        'korean' => '콜롬비아',
    ],
    'CG' => [
        'alpha3' => 'COG',
        'numeric' => 178,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Congo',
        'korean' => '콩고공화국',
    ],
    'CD' => [
        'alpha3' => 'COD',
        'numeric' => 180,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Democratic Republic of Congo',
        'korean' => '콩고민주공화국(DR콩고)',
    ],
    'CU' => [
        'alpha3' => 'CUB',
        'numeric' => 192,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Cuba',
        'korean' => '쿠바',
    ],
    'KW' => [
        'alpha3' => 'KWT',
        'numeric' => 414,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Kuwait',
        'korean' => '쿠웨이트',
    ],
    'CK' => [
        'alpha3' => 'COK',
        'numeric' => 184,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Cook Islands',
        'korean' => '쿡제도',
    ],
    'HR' => [
        'alpha3' => 'HRV',
        'numeric' => 191,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Croatia',
        'korean' => '크로아티아',
    ],
    'KG' => [
        'alpha3' => 'KGZ',
        'numeric' => 417,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Kyrgyz',
        'korean' => '키르기즈',
    ],
    'KI' => [
        'alpha3' => 'KIR',
        'numeric' => 296,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Kiribati',
        'korean' => '키리바시',
    ],
    'TJ' => [
        'alpha3' => 'TJK',
        'numeric' => 762,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Tajikistan',
        'korean' => '타지키스탄',
    ],
    'TZ' => [
        'alpha3' => 'TZA',
        'numeric' => 834,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Tanzania',
        'korean' => '탄자니아',
    ],
    'TH' => [
        'alpha3' => 'THA',
        'numeric' => 764,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Thailand',
        'korean' => '태국',
    ],
    'TR' => [
        'alpha3' => 'TUR',
        'numeric' => 792,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Turkey',
        'korean' => '터키',
    ],
    'TG' => [
        'alpha3' => 'TGO',
        'numeric' => 768,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '아프리카',
        'english' => 'Togo',
        'korean' => '토고',
    ],
    'TO' => [
        'alpha3' => 'TON',
        'numeric' => 776,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Tonga',
        'korean' => '통가',
    ],
    'TM' => [
        'alpha3' => 'TKM',
        'numeric' => 795,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '유럽',
        'english' => 'Turkmenistan',
        'korean' => '투르크메니스탄',
    ],
    'TV' => [
        'alpha3' => 'TUV',
        'numeric' => 798,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Tuvalu',
        'korean' => '투발루',
    ],
    'TN' => [
        'alpha3' => 'TUN',
        'numeric' => 788,
        'continent_common_eng' => 'Africa',
        'continent_common_kor' => '아프리카',
        'continent_mofa_kor' => '중동',
        'english' => 'Tunisia',
        'korean' => '튀니지',
    ],
    'TT' => [
        'alpha3' => 'TTO',
        'numeric' => 780,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Trinidad & Tobago',
        'korean' => '트리니다드토바고',
    ],
    'PA' => [
        'alpha3' => 'PAN',
        'numeric' => 591,
        'continent_common_eng' => 'North America',
        'continent_common_kor' => '북아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Panama',
        'korean' => '파나마',
    ],
    'PY' => [
        'alpha3' => 'PRY',
        'numeric' => 600,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Paraguay',
        'korean' => '파라과이',
    ],
    'PK' => [
        'alpha3' => 'PAK',
        'numeric' => 586,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Pakistan',
        'korean' => '파키스탄',
    ],
    'PG' => [
        'alpha3' => 'PNG',
        'numeric' => 598,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Papua New Guinea :PNG',
        'korean' => '파푸아뉴기니',
    ],
    'PW' => [
        'alpha3' => 'PLW',
        'numeric' => 585,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Palau',
        'korean' => '팔라우',
    ],
    'PS' => [
        'alpha3' => 'PSE',
        'numeric' => 275,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '중동',
        'english' => 'Palestine',
        'korean' => '팔레스타인',
    ],
    'PE' => [
        'alpha3' => 'PER',
        'numeric' => 604,
        'continent_common_eng' => 'South America',
        'continent_common_kor' => '남아메리카',
        'continent_mofa_kor' => '미주',
        'english' => 'Peru',
        'korean' => '페루',
    ],
    'PT' => [
        'alpha3' => 'PRT',
        'numeric' => 620,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Portugal',
        'korean' => '포르투갈',
    ],
    'PL' => [
        'alpha3' => 'POL',
        'numeric' => 616,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Poland',
        'korean' => '폴란드',
    ],
    'FR' => [
        'alpha3' => 'FRA',
        'numeric' => 250,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'France',
        'korean' => '프랑스',
    ],
    'FJ' => [
        'alpha3' => 'FJI',
        'numeric' => 242,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Fiji',
        'korean' => '피지',
    ],
    'FI' => [
        'alpha3' => 'FIN',
        'numeric' => 246,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Finland',
        'korean' => '핀란드',
    ],
    'PH' => [
        'alpha3' => 'PHL',
        'numeric' => 608,
        'continent_common_eng' => 'Asia',
        'continent_common_kor' => '아시아',
        'continent_mofa_kor' => '아주',
        'english' => 'Philippines',
        'korean' => '필리핀',
    ],
    'HU' => [
        'alpha3' => 'HUN',
        'numeric' => 348,
        'continent_common_eng' => 'Europe',
        'continent_common_kor' => '유럽',
        'continent_mofa_kor' => '유럽',
        'english' => 'Hungary',
        'korean' => '헝가리',
    ],
    'AU' => [
        'alpha3' => 'AUS',
        'numeric' => 36,
        'continent_common_eng' => 'Oceania',
        'continent_common_kor' => '오세아니아',
        'continent_mofa_kor' => '아주',
        'english' => 'Australia',
        'korean' => '호주',
    ],
];
